import type { ProductSize } from "@/types/ecommerce";

export type CatalogCategory = {
  id: string;
  name: string;
  slug: string;
  description: string;
};

export type CatalogProduct = {
  id: string;
  title: string;
  description: string;
  images: string[];
  category: string;
  brand: string;
  sizes: ProductSize[];
  stock: number;
  price: number;
  rating: number;
  featured: boolean;
  colorway: string;
  badge: string;
  imageUrl: string;
  detailHref?: string;
};

export type CatalogReview = {
  id: string;
  productId: string;
  userName: string;
  rating: number;
  comment: string;
};

export const catalogCategories: CatalogCategory[] = [
  {
    id: "jerseys",
    name: "Jerseys",
    slug: "jerseys",
    description: "Match-ready shirts, heritage kits, and tunnel-grade club style.",
  },
  {
    id: "astro-turf-football-boots",
    name: "Astro Turf Football Boots",
    slug: "astro-turf-football-boots",
    description: "Nike turf boots built for astro pitches, quick turns, and matchday control.",
  },
  {
    id: "mens-football-boots",
    name: "Men's Football Boots",
    slug: "mens-football-boots",
    description: "Elite Nike men's football boots for speed, power, touch, and modern pitch control.",
  },
  {
    id: "training",
    name: "Training",
    slug: "training",
    description: "Layers, gloves, bags, and everyday football equipment.",
  },
];

export const catalogProducts: CatalogProduct[] = [
  {
    id: "volt-strike-jersey",
    title: "Volt Strike Jersey",
    description:
      "A high-contrast match jersey with ventilated panels, sharp club energy, and a lightweight performance cut.",
    images: ["/images/products/volt-strike-jersey.webp"],
    category: "jerseys",
    brand: "RVSN Elite",
    sizes: ["S", "M", "L", "XL"],
    stock: 42,
    price: 89,
    rating: 4.8,
    featured: true,
    colorway: "from-lime-300 via-emerald-300 to-slate-950",
    badge: "Hot drop",
    imageUrl: "/images/products/volt-strike-jersey.webp",
  },
  {
    id: "night-derby-jersey",
    title: "Night Derby Jersey",
    description:
      "A cinematic away kit built for floodlights, city derbies, and sharp everyday styling.",
    images: ["/images/products/night-derby-jersey.avif", "/images/products/night-derby-jersey._1avif.avif" ,"/images/products/night-derby-jersey_2.avif"],
    category: "jerseys",
    brand: "RVSN Studio",
    sizes: ["XS", "S", "M", "L", "XL"],
    stock: 36,
    price: 95,
    rating: 4.7,
    featured: true,
    colorway: "from-sky-300 via-fuchsia-300 to-slate-950",
    badge: "City edition",
    imageUrl: "/images/products/night-derby-jersey.avif",
  },
  {
    id: "heritage-gold-jersey",
    title: "Heritage Gold Jersey",
    description:
      "A limited third kit with gold accents, deep red blocking, and a premium collector feel.",
    images: ["/images/products/heritage-gold-jersey.webp", "/images/products/heritage-gold-jersey_1.webp", "/images/products/heritage-gold-jersey_2.webp"],
    category: "jerseys",
    brand: "RVSN Archive",
    sizes: ["S", "M", "L", "XL", "XXL"],
    stock: 18,
    price: 109,
    rating: 4.9,
    featured: false,
    colorway: "from-amber-300 via-red-500 to-slate-950",
    badge: "Limited",
    imageUrl: "/images/products/heritage-gold-jersey.webp",
  },
   {
    id: "the_siujersey-red",
    title: "The Siu Jersey - Red",
    description:
      "The shield of Portugal and his iconic celebration, The Siu. His club history from Lisbon to Riyadh.",
    images: ["/images/products/the_siujersey-red.webp", "/images/products/the_siujersey-red_1.webp", "/images/products/the_siujersey-red_2.webp"],
    category: "jerseys",
    brand: "RVSN Archive",
    sizes: ["S", "M", "L", "XL", "XXL"],
    stock: 18,
    price: 109,
    rating: 4.9,
    featured: false,
    colorway: "from-amber-300 via-red-500 to-slate-950",
    badge: "Limited",
    imageUrl: "/images/products/the_siujersey-red.webp",
  },
   {
    id: "mexico_heritage_jersey",
    title: "Mexico Heritage Jersey (2026WC Edition) - Black",
    description:
      "A pattern inspired by Mexico's iconic 1998 jersey and the Mexican coat of arms with the eagle representing strength, the snake representing wisdom and the prickly pear cactus representing the Aztec capital city, Tenochtitlan.",
    images: ["/images/products/mexico_heritage_jersey.webp", "/images/products/mexico_heritage_jersey_1.webp", "/images/products/mexico_heritage_jersey_2.webp"],
    category: "jerseys",
    brand: "RVSN Archive",
    sizes: ["S", "M", "L", "XL", "XXL"],
    stock: 18,
    price: 109,
    rating: 4.9,
    featured: false,
    colorway: "from-amber-300 via-red-500 to-slate-950",
    badge: "Limited",
    imageUrl: "/images/products/mexico_heritage_jersey.webp",
  },
   {
    id: "the_parisians",
    title: "The Parisians (2025 European Champions) Away Jersey",
    description:
      "A bespoke jersey for PSG - your 2025 UCL champions.",
    images: ["/images/products/the_parisians.webp", "/images/products/the_parisians_1.webp", "/images/products/the_parisians_2.webp"],
    category: "jerseys",
    brand: "RVSN Archive",
    sizes: ["S", "M", "L", "XL", "XXL"],
    stock: 18,
    price: 99,
    rating: 4.9,
    featured: false,
    colorway: "from-amber-300 via-red-500 to-slate-950",
    badge: "Limited",
    imageUrl: "/images/products/the_parisians.webp",
  },
  {
    id: "nike-tiempo-ligera-pro-ib4477-100",
    title: "Nike Tiempo Ligera Pro",
    description:
      "Nike astro turf football boots built for sharp traction, quick turns, and confident matchday control. Style code: IB4477-100.",
    images: ["/images/products/nike-tiempo-ligera-pro-ib4477-100-1.jpg", "/images/products/nike-tiempo-ligera-pro-ib4477-100-2.jpg"],
    category: "astro-turf-football-boots",
    brand: "Nike",
    sizes: ["US 6", "US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    stock: 18,
    price: 169,
    rating: 4.9,
    featured: true,
    colorway: "from-violet-300 via-white to-slate-950",
    badge: "Pro turf",
    imageUrl: "/images/products/nike-tiempo-ligera-pro-ib4477-100-1.jpg",
  },
  {
    id: "nike-tiempo-ligera-pro-ib4477-010",
    title: "Nike Tiempo Ligera Pro",
    description:
      "Nike astro turf football boots built for sharp traction, quick turns, and confident matchday control. Style code: IB4477-010.",
    images: ["/images/products/nike-tiempo-ligera-pro-ib4477-010-1.jpg", "/images/products/nike-tiempo-ligera-pro-ib4477-010-2.jpg"],
    category: "astro-turf-football-boots",
    brand: "Nike",
    sizes: ["US 6", "US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    stock: 18,
    price: 169,
    rating: 4.9,
    featured: true,
    colorway: "from-violet-300 via-white to-slate-950",
    badge: "Pro turf",
    imageUrl: "/images/products/nike-tiempo-ligera-pro-ib4477-010-1.jpg",
  },
  {
    id: "nike-tiempo-ligera-pro-ib4477-002",
    title: "Nike Tiempo Ligera Pro",
    description:
      "Nike astro turf football boots built for sharp traction, quick turns, and confident matchday control. Style code: IB4477-002.",
    images: ["/images/products/nike-tiempo-ligera-pro-ib4477-002-1.jpg", "/images/products/nike-tiempo-ligera-pro-ib4477-002-2.jpg"],
    category: "astro-turf-football-boots",
    brand: "Nike",
    sizes: ["US 6", "US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    stock: 18,
    price: 169,
    rating: 4.9,
    featured: true,
    colorway: "from-violet-300 via-white to-slate-950",
    badge: "Pro turf",
    imageUrl: "/images/products/nike-tiempo-ligera-pro-ib4477-002-1.jpg",
  },
  {
    id: "nike-tiempo-ligera-pro-iq2384-901",
    title: "Nike Tiempo Ligera Pro",
    description:
      "Nike astro turf football boots built for sharp traction, quick turns, and confident matchday control. Style code: IQ2384-901.",
    images: ["/images/products/nike-tiempo-ligera-pro-iq2384-901-1.jpg", "/images/products/nike-tiempo-ligera-pro-iq2384-901-2.jpg"],
    category: "astro-turf-football-boots",
    brand: "Nike",
    sizes: ["US 6", "US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    stock: 18,
    price: 169,
    rating: 4.9,
    featured: true,
    colorway: "from-violet-300 via-white to-slate-950",
    badge: "Pro turf",
    imageUrl: "/images/products/nike-tiempo-ligera-pro-iq2384-901-1.jpg",
  },
  {
    id: "nike-united-phantom-6-low-academy-io8449-661",
    title: "Nike United Phantom 6 Low Academy",
    description:
      "Nike astro turf football boots built for sharp traction, quick turns, and confident matchday control. Style code: IO8449-661.",
    images: ["/images/products/nike-united-phantom-6-low-academy-io8449-661-1.jpg", "/images/products/nike-united-phantom-6-low-academy-io8449-661-2.jpg"],
    category: "astro-turf-football-boots",
    brand: "Nike",
    sizes: ["US 6", "US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    stock: 32,
    price: 99,
    rating: 4.7,
    featured: false,
    colorway: "from-violet-300 via-white to-slate-950",
    badge: "Academy",
    imageUrl: "/images/products/nike-united-phantom-6-low-academy-io8449-661-1.jpg",
  },
  {
    id: "nike-united-tiempo-maestro-academy-io8462-201",
    title: "Nike United Tiempo Maestro Academy",
    description:
      "Nike astro turf football boots built for sharp traction, quick turns, and confident matchday control. Style code: IO8462-201.",
    images: ["/images/products/nike-united-tiempo-maestro-academy-io8462-201-1.jpg", "/images/products/nike-united-tiempo-maestro-academy-io8462-201-2.jpg"],
    category: "astro-turf-football-boots",
    brand: "Nike",
    sizes: ["US 6", "US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    stock: 32,
    price: 99,
    rating: 4.7,
    featured: false,
    colorway: "from-violet-300 via-white to-slate-950",
    badge: "Academy",
    imageUrl: "/images/products/nike-united-tiempo-maestro-academy-io8462-201-1.jpg",
  },
  {
    id: "nike-jr-phantom-6-low-academy-hq2038-446",
    title: "Nike Jr. Phantom 6 Low Academy",
    description:
      "Nike astro turf football boots built for sharp traction, quick turns, and confident matchday control. Style code: HQ2038-446.",
    images: ["/images/products/nike-jr-phantom-6-low-academy-hq2038-446-1.jpg", "/images/products/nike-jr-phantom-6-low-academy-hq2038-446-2.jpg"],
    category: "astro-turf-football-boots",
    brand: "Nike",
    sizes: ["US 6", "US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    stock: 26,
    price: 99,
    rating: 4.7,
    featured: false,
    colorway: "from-violet-300 via-white to-slate-950",
    badge: "Academy",
    imageUrl: "/images/products/nike-jr-phantom-6-low-academy-hq2038-446-1.jpg",
  },
  {
    id: "nike-jr-phantom-6-low-academy-hq2038-001",
    title: "Nike Jr. Phantom 6 Low Academy",
    description:
      "Nike astro turf football boots built for sharp traction, quick turns, and confident matchday control. Style code: HQ2038-001.",
    images: ["/images/products/nike-jr-phantom-6-low-academy-hq2038-001-1.jpg", "/images/products/nike-jr-phantom-6-low-academy-hq2038-001-2.jpg"],
    category: "astro-turf-football-boots",
    brand: "Nike",
    sizes: ["US 6", "US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    stock: 26,
    price: 99,
    rating: 4.7,
    featured: false,
    colorway: "from-violet-300 via-white to-slate-950",
    badge: "Academy",
    imageUrl: "/images/products/nike-jr-phantom-6-low-academy-hq2038-001-1.jpg",
  },
  {
    id: "nike-phantom-6-high-academy-hq2277-446",
    title: "Nike Phantom 6 High Academy",
    description:
      "Nike astro turf football boots built for sharp traction, quick turns, and confident matchday control. Style code: HQ2277-446.",
    images: ["/images/products/nike-phantom-6-high-academy-hq2277-446-1.jpg", "/images/products/nike-phantom-6-high-academy-hq2277-446-2.jpg"],
    category: "astro-turf-football-boots",
    brand: "Nike",
    sizes: ["US 6", "US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    stock: 32,
    price: 99,
    rating: 4.7,
    featured: false,
    colorway: "from-violet-300 via-white to-slate-950",
    badge: "Academy",
    imageUrl: "/images/products/nike-phantom-6-high-academy-hq2277-446-1.jpg",
  },
  {
    id: "nike-phantom-6-low-pro-hj4123-446",
    title: "Nike Phantom 6 Low Pro",
    description:
      "Nike astro turf football boots built for sharp traction, quick turns, and confident matchday control. Style code: HJ4123-446.",
    images: ["/images/products/nike-phantom-6-low-pro-hj4123-446-1.jpg", "/images/products/nike-phantom-6-low-pro-hj4123-446-2.jpg"],
    category: "astro-turf-football-boots",
    brand: "Nike",
    sizes: ["US 6", "US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    stock: 18,
    price: 169,
    rating: 4.9,
    featured: true,
    colorway: "from-violet-300 via-white to-slate-950",
    badge: "Pro turf",
    imageUrl: "/images/products/nike-phantom-6-low-pro-hj4123-446-1.jpg",
  },
  {
    id: "nike-jr-phantom-6-high-academy-hq2049-446",
    title: "Nike Jr. Phantom 6 High Academy",
    description:
      "Nike astro turf football boots built for sharp traction, quick turns, and confident matchday control. Style code: HQ2049-446.",
    images: ["/images/products/nike-jr-phantom-6-high-academy-hq2049-446-1.jpg", "/images/products/nike-jr-phantom-6-high-academy-hq2049-446-2.jpg"],
    category: "astro-turf-football-boots",
    brand: "Nike",
    sizes: ["US 6", "US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    stock: 26,
    price: 99,
    rating: 4.7,
    featured: false,
    colorway: "from-violet-300 via-white to-slate-950",
    badge: "Academy",
    imageUrl: "/images/products/nike-jr-phantom-6-high-academy-hq2049-446-1.jpg",
  },
  {
    id: "nike-jr-phantom-6-high-academy-hq2049-001",
    title: "Nike Jr. Phantom 6 High Academy",
    description:
      "Nike astro turf football boots built for sharp traction, quick turns, and confident matchday control. Style code: HQ2049-001.",
    images: ["/images/products/nike-jr-phantom-6-high-academy-hq2049-001-1.jpg", "/images/products/nike-jr-phantom-6-high-academy-hq2049-001-2.jpg"],
    category: "astro-turf-football-boots",
    brand: "Nike",
    sizes: ["US 6", "US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    stock: 26,
    price: 99,
    rating: 4.7,
    featured: false,
    colorway: "from-violet-300 via-white to-slate-950",
    badge: "Academy",
    imageUrl: "/images/products/nike-jr-phantom-6-high-academy-hq2049-001-1.jpg",
  },
  {
    id: "nike-phantom-6-low-pro-erling-haaland-ih1788-603",
    title: "Nike Phantom 6 Low Pro 'Erling Haaland'",
    description:
      "Nike astro turf football boots built for sharp traction, quick turns, and confident matchday control. Style code: IH1788-603.",
    images: ["/images/products/nike-phantom-6-low-pro-erling-haaland-ih1788-603-1.jpg", "/images/products/nike-phantom-6-low-pro-erling-haaland-ih1788-603-2.jpg"],
    category: "astro-turf-football-boots",
    brand: "Nike",
    sizes: ["US 6", "US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    stock: 18,
    price: 169,
    rating: 4.9,
    featured: true,
    colorway: "from-violet-300 via-white to-slate-950",
    badge: "Haaland",
    imageUrl: "/images/products/nike-phantom-6-low-pro-erling-haaland-ih1788-603-1.jpg",
  },
  {
    id: "nike-tiempo-maestro-academy-ib4484-146",
    title: "Nike Tiempo Maestro Academy",
    description:
      "Nike astro turf football boots built for sharp traction, quick turns, and confident matchday control. Style code: IB4484-146.",
    images: ["/images/products/nike-tiempo-maestro-academy-ib4484-146-1.jpg", "/images/products/nike-tiempo-maestro-academy-ib4484-146-2.jpg"],
    category: "astro-turf-football-boots",
    brand: "Nike",
    sizes: ["US 6", "US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    stock: 32,
    price: 99,
    rating: 4.7,
    featured: false,
    colorway: "from-violet-300 via-white to-slate-950",
    badge: "Academy",
    imageUrl: "/images/products/nike-tiempo-maestro-academy-ib4484-146-1.jpg",
  },
  {
    id: "nike-phantom-6-low-club-hq2324-446",
    title: "Nike Phantom 6 Low Club",
    description:
      "Nike astro turf football boots built for sharp traction, quick turns, and confident matchday control. Style code: HQ2324-446.",
    images: ["/images/products/nike-phantom-6-low-club-hq2324-446-1.jpg", "/images/products/nike-phantom-6-low-club-hq2324-446-2.jpg"],
    category: "astro-turf-football-boots",
    brand: "Nike",
    sizes: ["US 6", "US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    stock: 32,
    price: 69,
    rating: 4.6,
    featured: false,
    colorway: "from-violet-300 via-white to-slate-950",
    badge: "Club",
    imageUrl: "/images/products/nike-phantom-6-low-club-hq2324-446-1.jpg",
  },
  {
    id: "nike-tiempo-maestro-club-ib4482-146",
    title: "Nike Tiempo Maestro Club",
    description:
      "Nike astro turf football boots built for sharp traction, quick turns, and confident matchday control. Style code: IB4482-146.",
    images: ["/images/products/nike-tiempo-maestro-club-ib4482-146-1.jpg", "/images/products/nike-tiempo-maestro-club-ib4482-146-2.jpg"],
    category: "astro-turf-football-boots",
    brand: "Nike",
    sizes: ["US 6", "US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    stock: 32,
    price: 69,
    rating: 4.6,
    featured: false,
    colorway: "from-violet-300 via-white to-slate-950",
    badge: "Club",
    imageUrl: "/images/products/nike-tiempo-maestro-club-ib4482-146-1.jpg",
  },
  {
    id: "nike-phantom-6-low-academy-hq2325-446",
    title: "Nike Phantom 6 Low Academy",
    description:
      "Nike astro turf football boots built for sharp traction, quick turns, and confident matchday control. Style code: HQ2325-446.",
    images: ["/images/products/nike-phantom-6-low-academy-hq2325-446-1.jpg", "/images/products/nike-phantom-6-low-academy-hq2325-446-2.jpg"],
    category: "astro-turf-football-boots",
    brand: "Nike",
    sizes: ["US 6", "US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    stock: 32,
    price: 99,
    rating: 4.7,
    featured: false,
    colorway: "from-violet-300 via-white to-slate-950",
    badge: "Academy",
    imageUrl: "/images/products/nike-phantom-6-low-academy-hq2325-446-1.jpg",
  },
  {
    id: "nike-phantom-6-low-academy-erling-haaland-hq2326-603",
    title: "Nike Phantom 6 Low Academy 'Erling Haaland'",
    description:
      "Nike astro turf football boots built for sharp traction, quick turns, and confident matchday control. Style code: HQ2326-603.",
    images: ["/images/products/nike-phantom-6-low-academy-erling-haaland-hq2326-603-1.jpg", "/images/products/nike-phantom-6-low-academy-erling-haaland-hq2326-603-2.jpg"],
    category: "astro-turf-football-boots",
    brand: "Nike",
    sizes: ["US 6", "US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    stock: 32,
    price: 99,
    rating: 4.7,
    featured: false,
    colorway: "from-violet-300 via-white to-slate-950",
    badge: "Haaland",
    imageUrl: "/images/products/nike-phantom-6-low-academy-erling-haaland-hq2326-603-1.jpg",
  },
  {
    id: "nike-jr-phantom-6-low-academy-erling-haaland-hq2040-603",
    title: "Nike Jr. Phantom 6 Low Academy 'Erling Haaland'",
    description:
      "Nike astro turf football boots built for sharp traction, quick turns, and confident matchday control. Style code: HQ2040-603.",
    images: ["/images/products/nike-jr-phantom-6-low-academy-erling-haaland-hq2040-603-1.jpg", "/images/products/nike-jr-phantom-6-low-academy-erling-haaland-hq2040-603-2.jpg"],
    category: "astro-turf-football-boots",
    brand: "Nike",
    sizes: ["US 6", "US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    stock: 26,
    price: 99,
    rating: 4.7,
    featured: false,
    colorway: "from-violet-300 via-white to-slate-950",
    badge: "Haaland",
    imageUrl: "/images/products/nike-jr-phantom-6-low-academy-erling-haaland-hq2040-603-1.jpg",
  },
  {
    id: "nike-jr-phantom-6-low-club-hq2006-446",
    title: "Nike Jr. Phantom 6 Low Club",
    description:
      "Nike astro turf football boots built for sharp traction, quick turns, and confident matchday control. Style code: HQ2006-446.",
    images: ["/images/products/nike-jr-phantom-6-low-club-hq2006-446-1.jpg", "/images/products/nike-jr-phantom-6-low-club-hq2006-446-2.jpg"],
    category: "astro-turf-football-boots",
    brand: "Nike",
    sizes: ["US 6", "US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    stock: 26,
    price: 69,
    rating: 4.6,
    featured: false,
    colorway: "from-violet-300 via-white to-slate-950",
    badge: "Club",
    imageUrl: "/images/products/nike-jr-phantom-6-low-club-hq2006-446-1.jpg",
  },
  {
    id: "nike-jr-tiempo-maestro-academy-ib5028-146",
    title: "Nike Jr. Tiempo Maestro Academy",
    description:
      "Nike astro turf football boots built for sharp traction, quick turns, and confident matchday control. Style code: IB5028-146.",
    images: ["/images/products/nike-jr-tiempo-maestro-academy-ib5028-146-1.jpg", "/images/products/nike-jr-tiempo-maestro-academy-ib5028-146-2.jpg"],
    category: "astro-turf-football-boots",
    brand: "Nike",
    sizes: ["US 6", "US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    stock: 26,
    price: 99,
    rating: 4.7,
    featured: false,
    colorway: "from-violet-300 via-white to-slate-950",
    badge: "Academy",
    imageUrl: "/images/products/nike-jr-tiempo-maestro-academy-ib5028-146-1.jpg",
  },
  {
    id: "nike-premier-3-hm0283-001",
    title: "Nike Premier 3",
    description:
      "Nike astro turf football boots built for sharp traction, quick turns, and confident matchday control. Style code: HM0283-001.",
    images: ["/images/products/nike-premier-3-hm0283-001-1.jpg", "/images/products/nike-premier-3-hm0283-001-2.jpg"],
    category: "astro-turf-football-boots",
    brand: "Nike",
    sizes: ["US 6", "US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    stock: 32,
    price: 119,
    rating: 4.6,
    featured: false,
    colorway: "from-violet-300 via-white to-slate-950",
    badge: "Turf",
    imageUrl: "/images/products/nike-premier-3-hm0283-001-1.jpg",
  },
  {
    id: "nike-phantom-6-low-pro-iq2155-900",
    title: "Nike Phantom 6 Low Pro",
    description:
      "Nike astro turf football boots built for sharp traction, quick turns, and confident matchday control. Style code: IQ2155-900.",
    images: ["/images/products/nike-phantom-6-low-pro-iq2155-900-1.jpg", "/images/products/nike-phantom-6-low-pro-iq2155-900-2.jpg"],
    category: "astro-turf-football-boots",
    brand: "Nike",
    sizes: ["US 6", "US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    stock: 18,
    price: 169,
    rating: 4.9,
    featured: true,
    colorway: "from-violet-300 via-white to-slate-950",
    badge: "Pro turf",
    imageUrl: "/images/products/nike-phantom-6-low-pro-iq2155-900-1.jpg",
  },
  {
    id: "nike-phantom-6-low-pro-hj4123-001",
    title: "Nike Phantom 6 Low Pro",
    description:
      "Nike astro turf football boots built for sharp traction, quick turns, and confident matchday control. Style code: HJ4123-001.",
    images: ["/images/products/nike-phantom-6-low-pro-hj4123-001-1.jpg", "/images/products/nike-phantom-6-low-pro-hj4123-001-2.jpg"],
    category: "astro-turf-football-boots",
    brand: "Nike",
    sizes: ["US 6", "US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    stock: 18,
    price: 169,
    rating: 4.9,
    featured: true,
    colorway: "from-violet-300 via-white to-slate-950",
    badge: "Pro turf",
    imageUrl: "/images/products/nike-phantom-6-low-pro-hj4123-001-1.jpg",
  },
  {
    id: "nike-jr-tiempo-maestro-flex-ib5030-007",
    title: "Nike Jr. Tiempo Maestro Flex",
    description:
      "Nike astro turf football boots built for sharp traction, quick turns, and confident matchday control. Style code: IB5030-007.",
    images: ["/images/products/nike-jr-tiempo-maestro-flex-ib5030-007-1.jpg", "/images/products/nike-jr-tiempo-maestro-flex-ib5030-007-2.jpg"],
    category: "astro-turf-football-boots",
    brand: "Nike",
    sizes: ["US 6", "US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    stock: 26,
    price: 59,
    rating: 4.6,
    featured: false,
    colorway: "from-violet-300 via-white to-slate-950",
    badge: "Turf",
    imageUrl: "/images/products/nike-jr-tiempo-maestro-flex-ib5030-007-1.jpg",
  },
  {
    id: "nike-jr-tiempo-maestro-flex-ib5030-600",
    title: "Nike Jr. Tiempo Maestro Flex",
    description:
      "Nike astro turf football boots built for sharp traction, quick turns, and confident matchday control. Style code: IB5030-600.",
    images: ["/images/products/nike-jr-tiempo-maestro-flex-ib5030-600-1.jpg", "/images/products/nike-jr-tiempo-maestro-flex-ib5030-600-2.jpg"],
    category: "astro-turf-football-boots",
    brand: "Nike",
    sizes: ["US 6", "US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    stock: 26,
    price: 59,
    rating: 4.6,
    featured: false,
    colorway: "from-violet-300 via-white to-slate-950",
    badge: "Turf",
    imageUrl: "/images/products/nike-jr-tiempo-maestro-flex-ib5030-600-1.jpg",
  },
  {
    id: "nike-phantom-6-low-academy-iq2399-900",
    title: "Nike Phantom 6 Low Academy",
    description:
      "Nike astro turf football boots built for sharp traction, quick turns, and confident matchday control. Style code: IQ2399-900.",
    images: ["/images/products/nike-phantom-6-low-academy-iq2399-900-1.jpg", "/images/products/nike-phantom-6-low-academy-iq2399-900-2.jpg"],
    category: "astro-turf-football-boots",
    brand: "Nike",
    sizes: ["US 6", "US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    stock: 32,
    price: 99,
    rating: 4.7,
    featured: false,
    colorway: "from-violet-300 via-white to-slate-950",
    badge: "Academy",
    imageUrl: "/images/products/nike-phantom-6-low-academy-iq2399-900-1.jpg",
  },
  {
    id: "nike-phantom-6-low-academy-hq2325-001",
    title: "Nike Phantom 6 Low Academy",
    description:
      "Nike astro turf football boots built for sharp traction, quick turns, and confident matchday control. Style code: HQ2325-001.",
    images: ["/images/products/nike-phantom-6-low-academy-hq2325-001-1.jpg", "/images/products/nike-phantom-6-low-academy-hq2325-001-2.jpg"],
    category: "astro-turf-football-boots",
    brand: "Nike",
    sizes: ["US 6", "US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    stock: 32,
    price: 99,
    rating: 4.7,
    featured: false,
    colorway: "from-violet-300 via-white to-slate-950",
    badge: "Academy",
    imageUrl: "/images/products/nike-phantom-6-low-academy-hq2325-001-1.jpg",
  },
  {
    id: "nike-phantom-6-high-club-hq2276-001",
    title: "Nike Phantom 6 High Club",
    description:
      "Nike astro turf football boots built for sharp traction, quick turns, and confident matchday control. Style code: HQ2276-001.",
    images: ["/images/products/nike-phantom-6-high-club-hq2276-001-1.jpg", "/images/products/nike-phantom-6-high-club-hq2276-001-2.jpg"],
    category: "astro-turf-football-boots",
    brand: "Nike",
    sizes: ["US 6", "US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    stock: 32,
    price: 69,
    rating: 4.6,
    featured: false,
    colorway: "from-violet-300 via-white to-slate-950",
    badge: "Club",
    imageUrl: "/images/products/nike-phantom-6-high-club-hq2276-001-1.jpg",
  },
  {
    id: "nike-phantom-6-low-club-hq2324-001",
    title: "Nike Phantom 6 Low Club",
    description:
      "Nike astro turf football boots built for sharp traction, quick turns, and confident matchday control. Style code: HQ2324-001.",
    images: ["/images/products/nike-phantom-6-low-club-hq2324-001-1.jpg", "/images/products/nike-phantom-6-low-club-hq2324-001-2.jpg"],
    category: "astro-turf-football-boots",
    brand: "Nike",
    sizes: ["US 6", "US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    stock: 32,
    price: 69,
    rating: 4.6,
    featured: false,
    colorway: "from-violet-300 via-white to-slate-950",
    badge: "Club",
    imageUrl: "/images/products/nike-phantom-6-low-club-hq2324-001-1.jpg",
  },
  {
    id: "nike-tiempo-maestro-club-ib4482-001",
    title: "Nike Tiempo Maestro Club",
    description:
      "Nike astro turf football boots built for sharp traction, quick turns, and confident matchday control. Style code: IB4482-001.",
    images: ["/images/products/nike-tiempo-maestro-club-ib4482-001-1.jpg", "/images/products/nike-tiempo-maestro-club-ib4482-001-2.jpg"],
    category: "astro-turf-football-boots",
    brand: "Nike",
    sizes: ["US 6", "US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    stock: 32,
    price: 69,
    rating: 4.6,
    featured: false,
    colorway: "from-violet-300 via-white to-slate-950",
    badge: "Club",
    imageUrl: "/images/products/nike-tiempo-maestro-club-ib4482-001-1.jpg",
  },
  {
    id: "nike-tiempo-maestro-club-iq2330-901",
    title: "Nike Tiempo Maestro Club",
    description:
      "Nike astro turf football boots built for sharp traction, quick turns, and confident matchday control. Style code: IQ2330-901.",
    images: ["/images/products/nike-tiempo-maestro-club-iq2330-901-1.jpg", "/images/products/nike-tiempo-maestro-club-iq2330-901-2.jpg"],
    category: "astro-turf-football-boots",
    brand: "Nike",
    sizes: ["US 6", "US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    stock: 32,
    price: 69,
    rating: 4.6,
    featured: false,
    colorway: "from-violet-300 via-white to-slate-950",
    badge: "Club",
    imageUrl: "/images/products/nike-tiempo-maestro-club-iq2330-901-1.jpg",
  },
  {
    id: "nike-tiempo-maestro-academy-ib4484-001",
    title: "Nike Tiempo Maestro Academy",
    description:
      "Nike astro turf football boots built for sharp traction, quick turns, and confident matchday control. Style code: IB4484-001.",
    images: ["/images/products/nike-tiempo-maestro-academy-ib4484-001-1.jpg", "/images/products/nike-tiempo-maestro-academy-ib4484-001-2.jpg"],
    category: "astro-turf-football-boots",
    brand: "Nike",
    sizes: ["US 6", "US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    stock: 32,
    price: 99,
    rating: 4.7,
    featured: false,
    colorway: "from-violet-300 via-white to-slate-950",
    badge: "Academy",
    imageUrl: "/images/products/nike-tiempo-maestro-academy-ib4484-001-1.jpg",
  },
  {
    id: "nike-tiempo-maestro-academy-iq2388-901",
    title: "Nike Tiempo Maestro Academy",
    description:
      "Nike astro turf football boots built for sharp traction, quick turns, and confident matchday control. Style code: IQ2388-901.",
    images: ["/images/products/nike-tiempo-maestro-academy-iq2388-901-1.jpg", "/images/products/nike-tiempo-maestro-academy-iq2388-901-2.jpg"],
    category: "astro-turf-football-boots",
    brand: "Nike",
    sizes: ["US 6", "US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    stock: 32,
    price: 99,
    rating: 4.7,
    featured: false,
    colorway: "from-violet-300 via-white to-slate-950",
    badge: "Academy",
    imageUrl: "/images/products/nike-tiempo-maestro-academy-iq2388-901-1.jpg",
  },  {
    id: "nike-mercurial-superfly-11-elite-se-ir0119-900",
    title: "Nike Mercurial Superfly 11 Elite SE",
    description:
      "Nike men's football boots built for speed, touch, and confident pitch control. Style code: IR0119-900.",
    images: ["/images/products/nike-mercurial-superfly-11-elite-se-ir0119-900-1.jpg", "/images/products/nike-mercurial-superfly-11-elite-se-ir0119-900-2.jpg"],
    category: "mens-football-boots",
    brand: "Nike",
    sizes: ["US 6", "US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    stock: 16,
    price: 279,
    rating: 4.9,
    featured: true,
    colorway: "from-violet-300 via-white to-slate-950",
    badge: "Speed",
    imageUrl: "/images/products/nike-mercurial-superfly-11-elite-se-ir0119-900-1.jpg",
  },  {
    id: "nike-mercurial-superfly-11-elite-io8219-900",
    title: "Nike Mercurial Superfly 11 Elite",
    description:
      "Nike men's football boots built for speed, touch, and confident pitch control. Style code: IO8219-900.",
    images: ["/images/products/nike-mercurial-superfly-11-elite-io8219-900-1.jpg", "/images/products/nike-mercurial-superfly-11-elite-io8219-900-2.jpg"],
    category: "mens-football-boots",
    brand: "Nike",
    sizes: ["US 6", "US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    stock: 16,
    price: 249,
    rating: 4.9,
    featured: true,
    colorway: "from-violet-300 via-white to-slate-950",
    badge: "Speed",
    imageUrl: "/images/products/nike-mercurial-superfly-11-elite-io8219-900-1.jpg",
  },  {
    id: "nike-mercurial-superfly-11-elite-if8507-001",
    title: "Nike Mercurial Superfly 11 Elite",
    description:
      "Nike men's football boots built for speed, touch, and confident pitch control. Style code: IF8507-001.",
    images: ["/images/products/nike-mercurial-superfly-11-elite-if8507-001-1.jpg", "/images/products/nike-mercurial-superfly-11-elite-if8507-001-2.jpg"],
    category: "mens-football-boots",
    brand: "Nike",
    sizes: ["US 6", "US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    stock: 16,
    price: 249,
    rating: 4.9,
    featured: true,
    colorway: "from-violet-300 via-white to-slate-950",
    badge: "Speed",
    imageUrl: "/images/products/nike-mercurial-superfly-11-elite-if8507-001-1.jpg",
  },  {
    id: "nike-mercurial-vapor-17-elite-se-ir0123-900",
    title: "Nike Mercurial Vapor 17 Elite SE",
    description:
      "Nike men's football boots built for speed, touch, and confident pitch control. Style code: IR0123-900.",
    images: ["/images/products/nike-mercurial-vapor-17-elite-se-ir0123-900-1.jpg", "/images/products/nike-mercurial-vapor-17-elite-se-ir0123-900-2.jpg"],
    category: "mens-football-boots",
    brand: "Nike",
    sizes: ["US 6", "US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    stock: 16,
    price: 279,
    rating: 4.9,
    featured: true,
    colorway: "from-violet-300 via-white to-slate-950",
    badge: "Speed",
    imageUrl: "/images/products/nike-mercurial-vapor-17-elite-se-ir0123-900-1.jpg",
  },  {
    id: "nike-mercurial-vapor-17-elite-io1560-900",
    title: "Nike Mercurial Vapor 17 Elite",
    description:
      "Nike men's football boots built for speed, touch, and confident pitch control. Style code: IO1560-900.",
    images: ["/images/products/nike-mercurial-vapor-17-elite-io1560-900-1.jpg", "/images/products/nike-mercurial-vapor-17-elite-io1560-900-2.jpg"],
    category: "mens-football-boots",
    brand: "Nike",
    sizes: ["US 6", "US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    stock: 16,
    price: 249,
    rating: 4.9,
    featured: true,
    colorway: "from-violet-300 via-white to-slate-950",
    badge: "Speed",
    imageUrl: "/images/products/nike-mercurial-vapor-17-elite-io1560-900-1.jpg",
  },  {
    id: "nike-mercurial-vapor-17-elite-if8508-001",
    title: "Nike Mercurial Vapor 17 Elite",
    description:
      "Nike men's football boots built for speed, touch, and confident pitch control. Style code: IF8508-001.",
    images: ["/images/products/nike-mercurial-vapor-17-elite-if8508-001-1.jpg", "/images/products/nike-mercurial-vapor-17-elite-if8508-001-2.jpg"],
    category: "mens-football-boots",
    brand: "Nike",
    sizes: ["US 6", "US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    stock: 16,
    price: 249,
    rating: 4.9,
    featured: true,
    colorway: "from-violet-300 via-white to-slate-950",
    badge: "Speed",
    imageUrl: "/images/products/nike-mercurial-vapor-17-elite-if8508-001-1.jpg",
  },  {
    id: "nike-mercurial-superfly-11-elite-se-ir0120-900",
    title: "Nike Mercurial Superfly 11 Elite SE",
    description:
      "Nike men's football boots built for speed, touch, and confident pitch control. Style code: IR0120-900.",
    images: ["/images/products/nike-mercurial-superfly-11-elite-se-ir0120-900-1.jpg", "/images/products/nike-mercurial-superfly-11-elite-se-ir0120-900-2.jpg"],
    category: "mens-football-boots",
    brand: "Nike",
    sizes: ["US 6", "US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    stock: 16,
    price: 279,
    rating: 4.9,
    featured: true,
    colorway: "from-violet-300 via-white to-slate-950",
    badge: "Speed",
    imageUrl: "/images/products/nike-mercurial-superfly-11-elite-se-ir0120-900-1.jpg",
  },  {
    id: "nike-mercurial-vapor-17-elite-se-ir0125-900",
    title: "Nike Mercurial Vapor 17 Elite SE",
    description:
      "Nike men's football boots built for speed, touch, and confident pitch control. Style code: IR0125-900.",
    images: ["/images/products/nike-mercurial-vapor-17-elite-se-ir0125-900-1.jpg", "/images/products/nike-mercurial-vapor-17-elite-se-ir0125-900-2.jpg"],
    category: "mens-football-boots",
    brand: "Nike",
    sizes: ["US 6", "US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    stock: 16,
    price: 279,
    rating: 4.9,
    featured: true,
    colorway: "from-violet-300 via-white to-slate-950",
    badge: "Speed",
    imageUrl: "/images/products/nike-mercurial-vapor-17-elite-se-ir0125-900-1.jpg",
  },  {
    id: "nike-tiempo-ligera-pro-hq3158-101",
    title: "Nike Tiempo Ligera Pro",
    description:
      "Nike men's football boots built for speed, touch, and confident pitch control. Style code: HQ3158-101.",
    images: ["/images/products/nike-tiempo-ligera-pro-hq3158-101-1.jpg", "/images/products/nike-tiempo-ligera-pro-hq3158-101-2.jpg"],
    category: "mens-football-boots",
    brand: "Nike",
    sizes: ["US 6", "US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    stock: 20,
    price: 169,
    rating: 4.8,
    featured: true,
    colorway: "from-violet-300 via-white to-slate-950",
    badge: "Touch",
    imageUrl: "/images/products/nike-tiempo-ligera-pro-hq3158-101-1.jpg",
  },  {
    id: "nike-tiempo-ligera-pro-hq3158-146",
    title: "Nike Tiempo Ligera Pro",
    description:
      "Nike men's football boots built for speed, touch, and confident pitch control. Style code: HQ3158-146.",
    images: ["/images/products/nike-tiempo-ligera-pro-hq3158-146-1.jpg", "/images/products/nike-tiempo-ligera-pro-hq3158-146-2.jpg"],
    category: "mens-football-boots",
    brand: "Nike",
    sizes: ["US 6", "US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    stock: 20,
    price: 169,
    rating: 4.8,
    featured: true,
    colorway: "from-violet-300 via-white to-slate-950",
    badge: "Touch",
    imageUrl: "/images/products/nike-tiempo-ligera-pro-hq3158-146-1.jpg",
  },  {
    id: "nike-tiempo-ligera-pro-io4400-901",
    title: "Nike Tiempo Ligera Pro",
    description:
      "Nike men's football boots built for speed, touch, and confident pitch control. Style code: IO4400-901.",
    images: ["/images/products/nike-tiempo-ligera-pro-io4400-901-1.jpg", "/images/products/nike-tiempo-ligera-pro-io4400-901-2.jpg"],
    category: "mens-football-boots",
    brand: "Nike",
    sizes: ["US 6", "US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    stock: 20,
    price: 169,
    rating: 4.8,
    featured: true,
    colorway: "from-violet-300 via-white to-slate-950",
    badge: "Touch",
    imageUrl: "/images/products/nike-tiempo-ligera-pro-io4400-901-1.jpg",
  },  {
    id: "nike-tiempo-ligera-pro-io9609-001",
    title: "Nike Tiempo Ligera Pro",
    description:
      "Nike men's football boots built for speed, touch, and confident pitch control. Style code: IO9609-001.",
    images: ["/images/products/nike-tiempo-ligera-pro-io9609-001-1.jpg", "/images/products/nike-tiempo-ligera-pro-io9609-001-2.jpg"],
    category: "mens-football-boots",
    brand: "Nike",
    sizes: ["US 6", "US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    stock: 20,
    price: 169,
    rating: 4.8,
    featured: true,
    colorway: "from-violet-300 via-white to-slate-950",
    badge: "Touch",
    imageUrl: "/images/products/nike-tiempo-ligera-pro-io9609-001-1.jpg",
  },  {
    id: "nike-tiempo-ligera-pro-hq3158-010",
    title: "Nike Tiempo Ligera Pro",
    description:
      "Nike men's football boots built for speed, touch, and confident pitch control. Style code: HQ3158-010.",
    images: ["/images/products/nike-tiempo-ligera-pro-hq3158-010-1.jpg", "/images/products/nike-tiempo-ligera-pro-hq3158-010-2.jpg"],
    category: "mens-football-boots",
    brand: "Nike",
    sizes: ["US 6", "US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    stock: 20,
    price: 169,
    rating: 4.8,
    featured: true,
    colorway: "from-violet-300 via-white to-slate-950",
    badge: "Touch",
    imageUrl: "/images/products/nike-tiempo-ligera-pro-hq3158-010-1.jpg",
  },  {
    id: "nike-phantom-6-low-elite-hj2146-001",
    title: "Nike Phantom 6 Low Elite",
    description:
      "Nike men's football boots built for speed, touch, and confident pitch control. Style code: HJ2146-001.",
    images: ["/images/products/nike-phantom-6-low-elite-hj2146-001-1.jpg", "/images/products/nike-phantom-6-low-elite-hj2146-001-2.jpg"],
    category: "mens-football-boots",
    brand: "Nike",
    sizes: ["US 6", "US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    stock: 16,
    price: 249,
    rating: 4.9,
    featured: true,
    colorway: "from-violet-300 via-white to-slate-950",
    badge: "Control",
    imageUrl: "/images/products/nike-phantom-6-low-elite-hj2146-001-1.jpg",
  },  {
    id: "nike-phantom-6-low-elite-ih1778-900",
    title: "Nike Phantom 6 Low Elite",
    description:
      "Nike men's football boots built for speed, touch, and confident pitch control. Style code: IH1778-900.",
    images: ["/images/products/nike-phantom-6-low-elite-ih1778-900-1.jpg", "/images/products/nike-phantom-6-low-elite-ih1778-900-2.jpg"],
    category: "mens-football-boots",
    brand: "Nike",
    sizes: ["US 6", "US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    stock: 16,
    price: 249,
    rating: 4.9,
    featured: true,
    colorway: "from-violet-300 via-white to-slate-950",
    badge: "Control",
    imageUrl: "/images/products/nike-phantom-6-low-elite-ih1778-900-1.jpg",
  },  {
    id: "nike-phantom-6-low-elite-hj2146-446",
    title: "Nike Phantom 6 Low Elite",
    description:
      "Nike men's football boots built for speed, touch, and confident pitch control. Style code: HJ2146-446.",
    images: ["/images/products/nike-phantom-6-low-elite-hj2146-446-1.jpg", "/images/products/nike-phantom-6-low-elite-hj2146-446-2.jpg"],
    category: "mens-football-boots",
    brand: "Nike",
    sizes: ["US 6", "US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    stock: 16,
    price: 249,
    rating: 4.9,
    featured: true,
    colorway: "from-violet-300 via-white to-slate-950",
    badge: "Control",
    imageUrl: "/images/products/nike-phantom-6-low-elite-hj2146-446-1.jpg",
  },  {
    id: "nike-phantom-6-high-elite-ih1779-900",
    title: "Nike Phantom 6 High Elite",
    description:
      "Nike men's football boots built for speed, touch, and confident pitch control. Style code: IH1779-900.",
    images: ["/images/products/nike-phantom-6-high-elite-ih1779-900-1.jpg", "/images/products/nike-phantom-6-high-elite-ih1779-900-2.jpg"],
    category: "mens-football-boots",
    brand: "Nike",
    sizes: ["US 6", "US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    stock: 16,
    price: 249,
    rating: 4.9,
    featured: true,
    colorway: "from-violet-300 via-white to-slate-950",
    badge: "Control",
    imageUrl: "/images/products/nike-phantom-6-high-elite-ih1779-900-1.jpg",
  },  {
    id: "nike-phantom-6-high-elite-hj2147-446",
    title: "Nike Phantom 6 High Elite",
    description:
      "Nike men's football boots built for speed, touch, and confident pitch control. Style code: HJ2147-446.",
    images: ["/images/products/nike-phantom-6-high-elite-hj2147-446-1.jpg", "/images/products/nike-phantom-6-high-elite-hj2147-446-2.jpg"],
    category: "mens-football-boots",
    brand: "Nike",
    sizes: ["US 6", "US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    stock: 16,
    price: 249,
    rating: 4.9,
    featured: true,
    colorway: "from-violet-300 via-white to-slate-950",
    badge: "Control",
    imageUrl: "/images/products/nike-phantom-6-high-elite-hj2147-446-1.jpg",
  },  {
    id: "nike-phantom-6-high-elite-hj2147-001",
    title: "Nike Phantom 6 High Elite",
    description:
      "Nike men's football boots built for speed, touch, and confident pitch control. Style code: HJ2147-001.",
    images: ["/images/products/nike-phantom-6-high-elite-hj2147-001-1.jpg", "/images/products/nike-phantom-6-high-elite-hj2147-001-2.jpg"],
    category: "mens-football-boots",
    brand: "Nike",
    sizes: ["US 6", "US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    stock: 16,
    price: 249,
    rating: 4.9,
    featured: true,
    colorway: "from-violet-300 via-white to-slate-950",
    badge: "Control",
    imageUrl: "/images/products/nike-phantom-6-high-elite-hj2147-001-1.jpg",
  },  {
    id: "nike-phantom-6-low-academy-hq2319-200",
    title: "Nike Phantom 6 Low Academy",
    description:
      "Nike men's football boots built for speed, touch, and confident pitch control. Style code: HQ2319-200.",
    images: ["/images/products/nike-phantom-6-low-academy-hq2319-200-1.jpg", "/images/products/nike-phantom-6-low-academy-hq2319-200-2.jpg"],
    category: "mens-football-boots",
    brand: "Nike",
    sizes: ["US 6", "US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    stock: 30,
    price: 99,
    rating: 4.7,
    featured: false,
    colorway: "from-violet-300 via-white to-slate-950",
    badge: "Control",
    imageUrl: "/images/products/nike-phantom-6-low-academy-hq2319-200-1.jpg",
  },  {
    id: "nike-phantom-6-low-academy-iq2398-900",
    title: "Nike Phantom 6 Low Academy",
    description:
      "Nike men's football boots built for speed, touch, and confident pitch control. Style code: IQ2398-900.",
    images: ["/images/products/nike-phantom-6-low-academy-iq2398-900-1.jpg", "/images/products/nike-phantom-6-low-academy-iq2398-900-2.jpg"],
    category: "mens-football-boots",
    brand: "Nike",
    sizes: ["US 6", "US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    stock: 30,
    price: 99,
    rating: 4.7,
    featured: false,
    colorway: "from-violet-300 via-white to-slate-950",
    badge: "Control",
    imageUrl: "/images/products/nike-phantom-6-low-academy-iq2398-900-1.jpg",
  },  {
    id: "nike-phantom-6-low-academy-hq2319-001",
    title: "Nike Phantom 6 Low Academy",
    description:
      "Nike men's football boots built for speed, touch, and confident pitch control. Style code: HQ2319-001.",
    images: ["/images/products/nike-phantom-6-low-academy-hq2319-001-1.jpg", "/images/products/nike-phantom-6-low-academy-hq2319-001-2.jpg"],
    category: "mens-football-boots",
    brand: "Nike",
    sizes: ["US 6", "US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    stock: 30,
    price: 99,
    rating: 4.7,
    featured: false,
    colorway: "from-violet-300 via-white to-slate-950",
    badge: "Control",
    imageUrl: "/images/products/nike-phantom-6-low-academy-hq2319-001-1.jpg",
  },  {
    id: "nike-tiempo-maestro-elite-hq3157-001",
    title: "Nike Tiempo Maestro Elite",
    description:
      "Nike men's football boots built for speed, touch, and confident pitch control. Style code: HQ3157-001.",
    images: ["/images/products/nike-tiempo-maestro-elite-hq3157-001-1.jpg", "/images/products/nike-tiempo-maestro-elite-hq3157-001-2.jpg"],
    category: "mens-football-boots",
    brand: "Nike",
    sizes: ["US 6", "US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    stock: 16,
    price: 249,
    rating: 4.9,
    featured: true,
    colorway: "from-violet-300 via-white to-slate-950",
    badge: "Touch",
    imageUrl: "/images/products/nike-tiempo-maestro-elite-hq3157-001-1.jpg",
  },  {
    id: "nike-tiempo-maestro-elite-ih1776-901",
    title: "Nike Tiempo Maestro Elite",
    description:
      "Nike men's football boots built for speed, touch, and confident pitch control. Style code: IH1776-901.",
    images: ["/images/products/nike-tiempo-maestro-elite-ih1776-901-1.jpg", "/images/products/nike-tiempo-maestro-elite-ih1776-901-2.jpg"],
    category: "mens-football-boots",
    brand: "Nike",
    sizes: ["US 6", "US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    stock: 16,
    price: 249,
    rating: 4.9,
    featured: true,
    colorway: "from-violet-300 via-white to-slate-950",
    badge: "Touch",
    imageUrl: "/images/products/nike-tiempo-maestro-elite-ih1776-901-1.jpg",
  },  {
    id: "nike-tiempo-maestro-elite-hq3157-146",
    title: "Nike Tiempo Maestro Elite",
    description:
      "Nike men's football boots built for speed, touch, and confident pitch control. Style code: HQ3157-146.",
    images: ["/images/products/nike-tiempo-maestro-elite-hq3157-146-1.jpg", "/images/products/nike-tiempo-maestro-elite-hq3157-146-2.jpg"],
    category: "mens-football-boots",
    brand: "Nike",
    sizes: ["US 6", "US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    stock: 16,
    price: 249,
    rating: 4.9,
    featured: true,
    colorway: "from-violet-300 via-white to-slate-950",
    badge: "Touch",
    imageUrl: "/images/products/nike-tiempo-maestro-elite-hq3157-146-1.jpg",
  },  {
    id: "nike-tiempo-ligera-pro-ib4474-100",
    title: "Nike Tiempo Ligera Pro",
    description:
      "Nike men's football boots built for speed, touch, and confident pitch control. Style code: IB4474-100.",
    images: ["/images/products/nike-tiempo-ligera-pro-ib4474-100-1.jpg", "/images/products/nike-tiempo-ligera-pro-ib4474-100-2.jpg"],
    category: "mens-football-boots",
    brand: "Nike",
    sizes: ["US 6", "US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    stock: 20,
    price: 169,
    rating: 4.8,
    featured: true,
    colorway: "from-violet-300 via-white to-slate-950",
    badge: "Touch",
    imageUrl: "/images/products/nike-tiempo-ligera-pro-ib4474-100-1.jpg",
  },  {
    id: "nike-tiempo-reactgato-hq3159-001",
    title: "Nike Tiempo Reactgato",
    description:
      "Nike men's football boots built for speed, touch, and confident pitch control. Style code: HQ3159-001.",
    images: ["/images/products/nike-tiempo-reactgato-hq3159-001-1.jpg", "/images/products/nike-tiempo-reactgato-hq3159-001-2.jpg"],
    category: "mens-football-boots",
    brand: "Nike",
    sizes: ["US 6", "US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    stock: 30,
    price: 89,
    rating: 4.6,
    featured: false,
    colorway: "from-violet-300 via-white to-slate-950",
    badge: "Touch",
    imageUrl: "/images/products/nike-tiempo-reactgato-hq3159-001-1.jpg",
  },  {
    id: "nike-tiempo-reactgato-hq3159-100",
    title: "Nike Tiempo Reactgato",
    description:
      "Nike men's football boots built for speed, touch, and confident pitch control. Style code: HQ3159-100.",
    images: ["/images/products/nike-tiempo-reactgato-hq3159-100-1.jpg", "/images/products/nike-tiempo-reactgato-hq3159-100-2.jpg"],
    category: "mens-football-boots",
    brand: "Nike",
    sizes: ["US 6", "US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    stock: 30,
    price: 89,
    rating: 4.6,
    featured: false,
    colorway: "from-violet-300 via-white to-slate-950",
    badge: "Touch",
    imageUrl: "/images/products/nike-tiempo-reactgato-hq3159-100-1.jpg",
  },  {
    id: "nike-united-phantom-6-low-elite-io8444-661",
    title: "Nike United Phantom 6 Low Elite",
    description:
      "Nike men's football boots built for speed, touch, and confident pitch control. Style code: IO8444-661.",
    images: ["/images/products/nike-united-phantom-6-low-elite-io8444-661-1.jpg", "/images/products/nike-united-phantom-6-low-elite-io8444-661-2.jpg"],
    category: "mens-football-boots",
    brand: "Nike",
    sizes: ["US 6", "US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    stock: 16,
    price: 249,
    rating: 4.9,
    featured: true,
    colorway: "from-violet-300 via-white to-slate-950",
    badge: "Control",
    imageUrl: "/images/products/nike-united-phantom-6-low-elite-io8444-661-1.jpg",
  },  {
    id: "nike-tiempo-streetgato-prm-hv3489-100",
    title: "Nike Tiempo Streetgato PRM",
    description:
      "Nike men's football boots built for speed, touch, and confident pitch control. Style code: HV3489-100.",
    images: ["/images/products/nike-tiempo-streetgato-prm-hv3489-100-1.jpg", "/images/products/nike-tiempo-streetgato-prm-hv3489-100-2.jpg"],
    category: "mens-football-boots",
    brand: "Nike",
    sizes: ["US 6", "US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    stock: 30,
    price: 89,
    rating: 4.6,
    featured: false,
    colorway: "from-violet-300 via-white to-slate-950",
    badge: "Touch",
    imageUrl: "/images/products/nike-tiempo-streetgato-prm-hv3489-100-1.jpg",
  },  {
    id: "nike-tiempo-streetgato-prm-iq2389-901",
    title: "Nike Tiempo Streetgato PRM",
    description:
      "Nike men's football boots built for speed, touch, and confident pitch control. Style code: IQ2389-901.",
    images: ["/images/products/nike-tiempo-streetgato-prm-iq2389-901-1.jpg", "/images/products/nike-tiempo-streetgato-prm-iq2389-901-2.jpg"],
    category: "mens-football-boots",
    brand: "Nike",
    sizes: ["US 6", "US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    stock: 30,
    price: 89,
    rating: 4.6,
    featured: false,
    colorway: "from-violet-300 via-white to-slate-950",
    badge: "Touch",
    imageUrl: "/images/products/nike-tiempo-streetgato-prm-iq2389-901-1.jpg",
  },  {
    id: "nike-tiempo-streetgato-hq7017-101",
    title: "Nike Tiempo Streetgato",
    description:
      "Nike men's football boots built for speed, touch, and confident pitch control. Style code: HQ7017-101.",
    images: ["/images/products/nike-tiempo-streetgato-hq7017-101-1.jpg", "/images/products/nike-tiempo-streetgato-hq7017-101-2.jpg"],
    category: "mens-football-boots",
    brand: "Nike",
    sizes: ["US 6", "US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    stock: 30,
    price: 89,
    rating: 4.6,
    featured: false,
    colorway: "from-violet-300 via-white to-slate-950",
    badge: "Touch",
    imageUrl: "/images/products/nike-tiempo-streetgato-hq7017-101-1.jpg",
  },  {
    id: "nike-tiempo-streetgato-hq7017-001",
    title: "Nike Tiempo Streetgato",
    description:
      "Nike men's football boots built for speed, touch, and confident pitch control. Style code: HQ7017-001.",
    images: ["/images/products/nike-tiempo-streetgato-hq7017-001-1.jpg", "/images/products/nike-tiempo-streetgato-hq7017-001-2.jpg"],
    category: "mens-football-boots",
    brand: "Nike",
    sizes: ["US 6", "US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    stock: 30,
    price: 89,
    rating: 4.6,
    featured: false,
    colorway: "from-violet-300 via-white to-slate-950",
    badge: "Touch",
    imageUrl: "/images/products/nike-tiempo-streetgato-hq7017-001-1.jpg",
  },  {
    id: "nike-total90-iq7631-001",
    title: "Nike Total90",
    description:
      "Nike men's football boots built for speed, touch, and confident pitch control. Style code: IQ7631-001.",
    images: ["/images/products/nike-total90-iq7631-001-1.jpg", "/images/products/nike-total90-iq7631-001-2.jpg"],
    category: "mens-football-boots",
    brand: "Nike",
    sizes: ["US 6", "US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    stock: 30,
    price: 119,
    rating: 4.6,
    featured: false,
    colorway: "from-violet-300 via-white to-slate-950",
    badge: "Heritage",
    imageUrl: "/images/products/nike-total90-iq7631-001-1.jpg",
  },  {
    id: "nike-mind-001-hq4307-400",
    title: "Nike Mind 001",
    description:
      "Nike men's football boots built for speed, touch, and confident pitch control. Style code: HQ4307-400.",
    images: ["/images/products/nike-mind-001-hq4307-400-1.jpg", "/images/products/nike-mind-001-hq4307-400-2.jpg"],
    category: "mens-football-boots",
    brand: "Nike",
    sizes: ["US 6", "US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    stock: 30,
    price: 119,
    rating: 4.6,
    featured: false,
    colorway: "from-violet-300 via-white to-slate-950",
    badge: "Recovery",
    imageUrl: "/images/products/nike-mind-001-hq4307-400-1.jpg",
  },  {
    id: "nike-mind-001-hq4307-003",
    title: "Nike Mind 001",
    description:
      "Nike men's football boots built for speed, touch, and confident pitch control. Style code: HQ4307-003.",
    images: ["/images/products/nike-mind-001-hq4307-003-1.jpg", "/images/products/nike-mind-001-hq4307-003-2.jpg"],
    category: "mens-football-boots",
    brand: "Nike",
    sizes: ["US 6", "US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    stock: 30,
    price: 119,
    rating: 4.6,
    featured: false,
    colorway: "from-violet-300 via-white to-slate-950",
    badge: "Recovery",
    imageUrl: "/images/products/nike-mind-001-hq4307-003-1.jpg",
  },  {
    id: "nike-mind-001-hq4307-300",
    title: "Nike Mind 001",
    description:
      "Nike men's football boots built for speed, touch, and confident pitch control. Style code: HQ4307-300.",
    images: ["/images/products/nike-mind-001-hq4307-300-1.jpg", "/images/products/nike-mind-001-hq4307-300-2.jpg"],
    category: "mens-football-boots",
    brand: "Nike",
    sizes: ["US 6", "US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    stock: 30,
    price: 119,
    rating: 4.6,
    featured: false,
    colorway: "from-violet-300 via-white to-slate-950",
    badge: "Recovery",
    imageUrl: "/images/products/nike-mind-001-hq4307-300-1.jpg",
  },  {
    id: "nike-phantom-6-low-elite-lv8-io8217-008",
    title: "Nike Phantom 6 Low Elite LV8",
    description:
      "Nike men's football boots built for speed, touch, and confident pitch control. Style code: IO8217-008.",
    images: ["/images/products/nike-phantom-6-low-elite-lv8-io8217-008-1.jpg", "/images/products/nike-phantom-6-low-elite-lv8-io8217-008-2.jpg"],
    category: "mens-football-boots",
    brand: "Nike",
    sizes: ["US 6", "US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    stock: 16,
    price: 279,
    rating: 4.9,
    featured: true,
    colorway: "from-violet-300 via-white to-slate-950",
    badge: "Control",
    imageUrl: "/images/products/nike-phantom-6-low-elite-lv8-io8217-008-1.jpg",
  },  {
    id: "nike-mercurial-superfly-11-pro-io8224-900",
    title: "Nike Mercurial Superfly 11 Pro",
    description:
      "Nike men's football boots built for speed, touch, and confident pitch control. Style code: IO8224-900.",
    images: ["/images/products/nike-mercurial-superfly-11-pro-io8224-900-1.jpg", "/images/products/nike-mercurial-superfly-11-pro-io8224-900-2.jpg"],
    category: "mens-football-boots",
    brand: "Nike",
    sizes: ["US 6", "US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    stock: 20,
    price: 169,
    rating: 4.8,
    featured: true,
    colorway: "from-violet-300 via-white to-slate-950",
    badge: "Speed",
    imageUrl: "/images/products/nike-mercurial-superfly-11-pro-io8224-900-1.jpg",
  },  {
    id: "nike-mercurial-superfly-11-pro-if8509-001",
    title: "Nike Mercurial Superfly 11 Pro",
    description:
      "Nike men's football boots built for speed, touch, and confident pitch control. Style code: IF8509-001.",
    images: ["/images/products/nike-mercurial-superfly-11-pro-if8509-001-1.jpg", "/images/products/nike-mercurial-superfly-11-pro-if8509-001-2.jpg"],
    category: "mens-football-boots",
    brand: "Nike",
    sizes: ["US 6", "US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    stock: 20,
    price: 169,
    rating: 4.8,
    featured: true,
    colorway: "from-violet-300 via-white to-slate-950",
    badge: "Speed",
    imageUrl: "/images/products/nike-mercurial-superfly-11-pro-if8509-001-1.jpg",
  },  {
    id: "nike-mercurial-vapor-17-academy-io8228-900",
    title: "Nike Mercurial Vapor 17 Academy",
    description:
      "Nike men's football boots built for speed, touch, and confident pitch control. Style code: IO8228-900.",
    images: ["/images/products/nike-mercurial-vapor-17-academy-io8228-900-1.jpg", "/images/products/nike-mercurial-vapor-17-academy-io8228-900-2.jpg"],
    category: "mens-football-boots",
    brand: "Nike",
    sizes: ["US 6", "US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    stock: 30,
    price: 99,
    rating: 4.7,
    featured: false,
    colorway: "from-violet-300 via-white to-slate-950",
    badge: "Speed",
    imageUrl: "/images/products/nike-mercurial-vapor-17-academy-io8228-900-1.jpg",
  },  {
    id: "nike-mercurial-vapor-17-academy-if8517-001",
    title: "Nike Mercurial Vapor 17 Academy",
    description:
      "Nike men's football boots built for speed, touch, and confident pitch control. Style code: IF8517-001.",
    images: ["/images/products/nike-mercurial-vapor-17-academy-if8517-001-1.jpg", "/images/products/nike-mercurial-vapor-17-academy-if8517-001-2.jpg"],
    category: "mens-football-boots",
    brand: "Nike",
    sizes: ["US 6", "US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    stock: 30,
    price: 99,
    rating: 4.7,
    featured: false,
    colorway: "from-violet-300 via-white to-slate-950",
    badge: "Speed",
    imageUrl: "/images/products/nike-mercurial-vapor-17-academy-if8517-001-1.jpg",
  },  {
    id: "nike-phantom-6-low-elite-hq2335-446",
    title: "Nike Phantom 6 Low Elite",
    description:
      "Nike men's football boots built for speed, touch, and confident pitch control. Style code: HQ2335-446.",
    images: ["/images/products/nike-phantom-6-low-elite-hq2335-446-1.jpg", "/images/products/nike-phantom-6-low-elite-hq2335-446-2.jpg"],
    category: "mens-football-boots",
    brand: "Nike",
    sizes: ["US 6", "US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    stock: 16,
    price: 249,
    rating: 4.9,
    featured: true,
    colorway: "from-violet-300 via-white to-slate-950",
    badge: "Control",
    imageUrl: "/images/products/nike-phantom-6-low-elite-hq2335-446-1.jpg",
  },  {
    id: "nike-phantom-6-low-elite-hq2335-001",
    title: "Nike Phantom 6 Low Elite",
    description:
      "Nike men's football boots built for speed, touch, and confident pitch control. Style code: HQ2335-001.",
    images: ["/images/products/nike-phantom-6-low-elite-hq2335-001-1.jpg", "/images/products/nike-phantom-6-low-elite-hq2335-001-2.jpg"],
    category: "mens-football-boots",
    brand: "Nike",
    sizes: ["US 6", "US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    stock: 16,
    price: 249,
    rating: 4.9,
    featured: true,
    colorway: "from-violet-300 via-white to-slate-950",
    badge: "Control",
    imageUrl: "/images/products/nike-phantom-6-low-elite-hq2335-001-1.jpg",
  },  {
    id: "nike-phantom-6-low-elite-iq1870-900",
    title: "Nike Phantom 6 Low Elite",
    description:
      "Nike men's football boots built for speed, touch, and confident pitch control. Style code: IQ1870-900.",
    images: ["/images/products/nike-phantom-6-low-elite-iq1870-900-1.jpg", "/images/products/nike-phantom-6-low-elite-iq1870-900-2.jpg"],
    category: "mens-football-boots",
    brand: "Nike",
    sizes: ["US 6", "US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    stock: 16,
    price: 249,
    rating: 4.9,
    featured: true,
    colorway: "from-violet-300 via-white to-slate-950",
    badge: "Control",
    imageUrl: "/images/products/nike-phantom-6-low-elite-iq1870-900-1.jpg",
  },  {
    id: "nike-mercurial-superfly-11-academy-io8227-900",
    title: "Nike Mercurial Superfly 11 Academy",
    description:
      "Nike men's football boots built for speed, touch, and confident pitch control. Style code: IO8227-900.",
    images: ["/images/products/nike-mercurial-superfly-11-academy-io8227-900-1.jpg", "/images/products/nike-mercurial-superfly-11-academy-io8227-900-2.jpg"],
    category: "mens-football-boots",
    brand: "Nike",
    sizes: ["US 6", "US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    stock: 30,
    price: 99,
    rating: 4.7,
    featured: false,
    colorway: "from-violet-300 via-white to-slate-950",
    badge: "Speed",
    imageUrl: "/images/products/nike-mercurial-superfly-11-academy-io8227-900-1.jpg",
  },  {
    id: "nike-mercurial-superfly-11-academy-io1485-001",
    title: "Nike Mercurial Superfly 11 Academy",
    description:
      "Nike men's football boots built for speed, touch, and confident pitch control. Style code: IO1485-001.",
    images: ["/images/products/nike-mercurial-superfly-11-academy-io1485-001-1.jpg", "/images/products/nike-mercurial-superfly-11-academy-io1485-001-2.jpg"],
    category: "mens-football-boots",
    brand: "Nike",
    sizes: ["US 6", "US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    stock: 30,
    price: 99,
    rating: 4.7,
    featured: false,
    colorway: "from-violet-300 via-white to-slate-950",
    badge: "Speed",
    imageUrl: "/images/products/nike-mercurial-superfly-11-academy-io1485-001-1.jpg",
  },  {
    id: "rain-ready-training-layer",
    title: "Rain Ready Training Layer",
    description:
      "A lightweight weather layer with stretch panels, quiet finish, and matchday-ready zip storage.",
    images: ["/images/products/rain-ready-training-layer.webp"],
    category: "training",
    brand: "RVSN Training",
    sizes: ["S", "M", "L", "XL"],
    stock: 51,
    price: 129,
    rating: 4.5,
    featured: false,
    colorway: "from-emerald-300 via-slate-200 to-slate-950",
    badge: "Training",
    imageUrl: "/images/products/rain-ready-training-layer.webp",
  },
  {
    id: "elite-grip-gloves",
    title: "Elite Grip Goalkeeper Gloves",
    description:
      "Premium latex goalkeeper gloves with a wrapped thumb, negative cut, and wet-weather contact grip.",
    images: ["/images/products/elite-grip-gloves.webp"],
    category: "training",
    brand: "Keeper Union",
    sizes: ["S", "M", "L", "XL"],
    stock: 22,
    price: 79,
    rating: 4.6,
    featured: true,
    colorway: "from-lime-300 via-white to-slate-950",
    badge: "Grip",
    imageUrl: "/images/products/elite-grip-gloves.webp",
  },
   {
    id: "adidas_predator_training_gloves",
    title: "Adidas Predator Training Gloves",
    description:
      "adidas Predator Training goalkeeper gloves mounted on a flat cut in White-Lucid lemon colourway.",
    images: ["/images/products/adidas_predator_training_gloves.webp", "/images/products/adidas_predator_training_gloves_1.webp", "/images/products/adidas_predator_training_gloves_2.webp"],
    category: "training",
    brand: "Keeper Union",
    sizes: ["S", "M", "L", "XL"],
    stock: 22,
    price: 79,
    rating: 4.6,
    featured: true,
    colorway: "from-lime-300 via-white to-slate-950",
    badge: "Grip",
    imageUrl: "/images/products/adidas_predator_training_gloves.webp",
  },
   {
    id: "adidas_copa_match_fingersave_gloves",
    title: "Adidas Copa Match Fingersave Gloves",
    description:
      "Premium latex goalkeeper gloves with a wrapped thumb, negative cut, and wet-weather contact grip.",
    images: ["/images/products/adidas_copa_match_fingersave_gloves.webp" ,"/images/products/adidas_copa_match_fingersave_gloves_1.webp", "/images/products/adidas_copa_match_fingersave_gloves_2.webp"],
    category: "training",
    brand: "Keeper Union",
    sizes: ["S", "M", "L", "XL"],
    stock: 22,
    price: 50,
    rating: 4.8,
    featured: true,
    colorway: "from-lime-300 via-white to-slate-950",
    badge: "Grip",
    imageUrl: "/images/products/adidas_copa_match_fingersave_gloves.webp",
  },
];

export const catalogReviews: CatalogReview[] = [
  {
    id: "review-1",
    productId: "volt-strike-jersey",
    userName: "Omar A.",
    rating: 5,
    comment: "Feels elite and the color pops under lights. The fit is sharp without being too tight.",
  },
  {
    id: "review-2",
    productId: "volt-strike-jersey",
    userName: "Daniel R.",
    rating: 4,
    comment: "Great material and premium look. I would size up if you like a looser street fit.",
  },
  {
    id: "review-3",
    productId: "nike-phantom-6-low-pro-hj4123-446",
    userName: "Maya K.",
    rating: 5,
    comment: "Very light, responsive, and the sole feels fast on astro turf.",
  },
  {
    id: "review-4",
    productId: "nike-phantom-6-low-pro-erling-haaland-ih1788-603",
    userName: "Yousef M.",
    rating: 5,
    comment: "The strike feel is excellent. These feel made for shooting practice.",
  },
];

export function getCatalogProduct(productId: string) {
  return catalogProducts.find((product) => product.id === productId) ?? null;
}

export function getCatalogCategory(slug: string) {
  return catalogCategories.find((category) => category.slug === slug) ?? null;
}

export function getProductsByCatalogCategory(slug: string) {
  return catalogProducts.filter((product) => product.category === slug);
}

export function getRelatedCatalogProducts(product: CatalogProduct) {
  return catalogProducts
    .filter((item) => item.id !== product.id && (item.category === product.category || item.brand === product.brand))
    .slice(0, 4);
}

export function getCatalogReviews(productId: string) {
  return catalogReviews.filter((review) => review.productId === productId);
}



